# Generated by Django 5.1.2 on 2025-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
